name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: /templates/nginx.nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: bin
    group: wheel
    mode: '0644'

name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started
